### ISSUE TITLE
Feature Request: Memory specifications

### ISSUE THREAD

**Issue by carlwitt** [wrench-project/wrench#1]
I've been looking for a way to specify the amount of main memory per compute node, but haven't found one in here (like in SimGrid). Am I missing something, or is this intentional?

**Comment by rafaelfsilva** [comment]
Hi Carl,

Thanks for you contact. WRENCH is still under development (we plan a first alpha release soon). So, things may break during our developments.

WRENCH uses SimGrid platform files, so you can describe memory capacities via the 'prop' attribute as in the example available in: ```https://github.com/simgrid/simgrid/blob/master/examples/platforms/prop.xml```

Do you have any specific use case in mind, so we can guide you, and also our development tasks?

Thanks,
Rafael

**Comment by henricasanova** [comment]
Let me add that at the moment WRENCH ignores the memory capacity, but that will change soon-ish, perhaps after the first release though.
thanks
henri

**Comment by carlwitt** [comment]
I'm working on our Hadoop-based scientific workflow management system [Hi-WAY](https://github.com/carlwitt/Hi-WAY). My current goal is to develop resource allocation strategies for workflows. I would like to complement my real-world experiments with simulations. 

So far, I've been looking into CloudSim (and WorkflowSim), as well as Hadoop specific simulation environments (such as YARNSim [1] and ABS-YARN [2]) but SimGrid seems to be one of the most mature systems.

Thanks for the pointer and the quick reply. I'll have a look again into SimGrid and especially WRENCH. In case I take a deeper dive into the simulation topic, I'd be interested in adding memory support to wrench.

[1]	N. Liu, X. Yang, X.-H. Sun, J. Jenkins, and R. B. Ross, “YARNsim: Simulating Hadoop YARN.,” CCGRID, pp. 637–646, 2015.
[2]	J.-C. Lin, I. C. Yu, E. B. Johnsen, and M.-C. Lee, “ABS-YARN: A Formal Framework for Modeling Hadoop YARN Clusters.,” FASE, pp. 49–65, 2016.

**Comment by henricasanova** [comment]
SimGrid is the most mature in terms of simulation accuracy and scalability, by a long shot. However, unlike these other projects, SimGrid has traditionally been seen as harder to use due to it provided lower-level abstractions.  One of the goals of WRENCH is to remedy this situation by (i) benefiting from the great accuracy and scalability afforded by SimGrid; and (ii) provided a convenient abstraction layer for people doing Workflow research.   So you do seem like a prime candidate user for WRENCH, which is great. You may actually need some "Hadoop compute service" abstraction in WRENCH if you research is dependent on Hadoop. This is something that can be done eventually, but is of course a much bigger undertaking than adding memory support to WRENCH.

You're catching us at crunch time before our first release (with limited functionalities).  But in the meantime though, feel free to ask us whatever SimGrid/WRENCH questions, and stay tuned for more WRENCH news.
