### ISSUE TITLE
Logs include color-changing ASCII codes even when logs are disabled

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#104]

**Comment by henricasanova** [comment]
fixed.

**Comment by ryantanaka** [comment]
hey @henricasanova, so this issue refers to https://github.com/wrench-project/wrench/commit/5e840ffd9c00bb5514aa4731e59fc4298625ea0e right?

In one of my activities, I run wrench like this: 
```
CMD ./simulator_remote_storage 10 \
         --log="root.fmt:[%d][%h:%t]%e%m%n" \
         --log=root.thresh:critical \
         --log=wms.thresh:debug \
         --log=simple_wms.thresh:debug \
         --log=simple_wms_scheduler.thresh:debug
```
And I get no color. But, running `./simulator_remote_storage 10`, I do get color in the terminal. 

In the following functions, when I remove the `not`s, then I get the correct color always. 
https://github.com/wrench-project/wrench/blob/f3f10f7a3a4779b18cf456609b98eac40647f623/src/wrench/logging/TerminalOutput.cpp#L41-L57

I want to make sure that change won't break anything else since I don't have any context for this issue. 

Thanks!

**Comment by henricasanova** [comment]
Let me investigate.... seems that colors are broken a bit.

**Comment by henricasanova** [comment]
Just pushed a fix. Let me know if it addresses your bug.

**Comment by ryantanaka** [comment]
ok thanks, it works now

**Comment by henricasanova** [comment]
The fix above works when logs are controlled by command-line arguments, but not when the code disables logging programmatically (like in unit_tests!)
