### ISSUE TITLE
Workflow parsers not available outside WRENCH directory

### ISSUE THREAD

**Issue by frs69wq** [wrench-project/wrench#117]
Hi guys, 
It seems that the Workflow::loadFrom* functions are in the process to be replaced by wrench::PegasusWorkflowParser::createWorkflowFrom* ones. However, the header file describing is in tools/pegasus and thus not in the default list of include paths. 
The examples shipped with Wrench use a relative path to include it ("../tools ...")
Finally, the new parsers are in the seperated lib which does not seem to be handled by CMake (yet).
Question is, how can one load a workflow with the current version of the 1.5-dev master? (I uncommented the loadFromDAX I need, but ... ;))
Cheers
Fred

**Comment by henricasanova** [comment]
Yes, we are in the process of removing the parsing stuff out of WRENCH, and in the meantime it's in a separate library. You make good points, and here is what I did in the latest commit that references that issue: 
  - The header is now included in "wrench.h", which is in the default path
  - The examples no longer us a relative path (that was something CLion did on its own, and I never noticed)
  - You don't care, but I've fixed the wrench-init so that it works with clouds (due to our new semantics)
 
I am not sure about your comment "the new parsers are in the seperated lib which does not seem to be handled by CMake".  My CMake compiles and installs both libraries... what is the problem exactly? 

In answer to your question, you just need to, after a make install, to do:

#include <wrench.h> 
auto workflow = wrench::PegasusWorkflowParser::createWorkflowFromDAXorJSON("stuff.dax", "1000Gf")

Let me know if that doesn't work. 

Also, right now many Pegasus JSON files are broken due to weird output file sharing, and the need for us to implement ways to deal with Pegasus-specific " auxiliary" and "transfer"  tasks. Hopefully you're using DAX files...

**Comment by frs69wq** [comment]
I think part of the issue came from a shaky install on my side, which is now solved. After an update to my CMakeLists.txt to load the parser library it also links well. 
My comment about CMake was that when configuring the paths to the different required libraries, I didn't see an entry to set a custom path for the parser library if it's not installed in the default place. That too is now ok, hence closing the issue. 
Thx.
