### ISSUE TITLE
Wrench not finding the git version of SimGrid (cmake bug)

### ISSUE THREAD

**Issue by mquinson** [wrench-project/wrench#144]
Hello,

we recently decided to enter the 21th century in SimGrid, and install the library in the Right Location, which is distro-dependent. Under Debian, libraries are to be installed under /usr/lib/x86_64-linux-gnu/ to allow multi-arch installations. Under Fedora IIRC, simgrid will land under /usr/lib64 or something. 

As a result, you cannot search for SimGrid with a simple ```find_library(SIMGRID_LIBRARY NAMES simgrid HINTS ${SIMGRID_INSTALL_PATH}/lib NO_DEFAULT_PATH)``` anymore, sorry about that.

You should probably use the FindSimGrid.cmake module, that is provided in https://simgrid.frama.io/simgrid/Start_Your_Own_Project.html#building-your-project-with-cmake Sorry for the inconvenience... 

Once this is fixed, we should find a solution to fix our CI that test that your code runs on our git. This is how I detected the whole issue, thanks to https://framagit.org/simgrid/external-projects-ci/-/jobs/684711

Thanks for your help in improving SimGrid,

**Comment by henricasanova** [comment]
I've moved WRENCH's build process to using FindSimGrid.cmake. It's for now in a branch called simgrid_cmake (and of course, as usual, I forgot to reference this issue's number in most of my commit messages... sigh).   It all seems to work (tried it on a few platforms), and makes our CMakeList.txt much nicer. 

I've added the FindSimGrid.cmake file to the conf/cmake directory, so we'll have to occasionally update it with the latest version in the simgrid repo, as advised on the Web page references above by Martin. 

To avoid cut-and-pasting content of this file, I've re-factored wrench-init a bit, generating the script at compile time so that it is self-contained. It's a bit clunky, but it works and I couldn't think of an easier way. 

I am going to merge this into the wrench master (and then propagate the change to the simgrid-CI branch of wrench).
 
I am closing this issue for now.
