### ISSUE TITLE
Development of WRENCH dashboard

### ISSUE THREAD

**Issue by rafaelfsilva** [wrench-project/wrench#82]

**Comment by ryantanaka** [comment]
### notes on features that can be added to the dashboard

1. In addition to the task gantt chart graph (task id on the y axis and time on the x axis) we have now, it would be useful to add a "host view" where **hostname is on the y-axis and time is on the x-axis**. This could show up on the dashboard as another graph along side the task gantt chart graph, or we could have a button that switches between views. If you guys can get this working with d3 transitions, that would be pretty cool. 

![untitled diagram](https://user-images.githubusercontent.com/19616012/52150620-ac188400-2614-11e9-9c33-369f6b9147f5.png)

Here is an example of what that might look like. Here, Host1 runs Task1. Host2 runs Task2, then starts Task3 while Task2 is still running (probably because Host2 has 2 cores). And Host3 starts two tasks in parallel as well. The tricky part with this graph is figuring out a nice way to display tasks running in parallel on a host. Do we overlap them like how it's done with Host2 or split them up nicely like how it's shown for Host3? 

2. Energy visualization. The functions to get energy data are just about done and will be ready once #88 is closed.

3. Workflow visualization. The code bellow just needs to be added into the dashboard. 

https://github.com/wrench-project/wrench-pedagogic-modules/blob/4486d84ea2268722b5833652f996083f1cb4df6f/visualization/public/scripts/graphs.js#L355-L494

4. Platform visualization. It would be useful to have a visualization similar to the one presented on the [SimGrid site](https://github.com/wrench-project/wrench-pedagogic-modules/blob/4486d84ea2268722b5833652f996083f1cb4df6f/visualization/public/scripts/graphs.js#L355-L494) in section **4.5 A network topology plot**. In this visualization, nodes will be either network links or hosts and edges will be the connections between links and nodes. A useful feature for this visualization would be to allow the user to click on two or more hosts to reveal the routes between them (these are the routes specified in the platform.xml we give to the simulation). Routes that are revealed this way could be given some special color to stand out. I can take care of writing the function to get the platform/route information as a JSON file. 

5. Placing the dashboard in a docker container so users can just run something like `docker pull wrenchproject/wrench:1.4-dashboard` to get it.

**Comment by ryantanaka** [comment]
@gjethwani 

Regarding the energy visualization, when a user calls `SimulationOutput::dumpHostEnergyConsumptionJSON(std::string file_path)`, information will be gathered from the simulation and dumped as JSON in the following format:

![screen shot 2019-03-01 at 1 35 25 pm](https://user-images.githubusercontent.com/19616012/53672506-f9ddd780-3c26-11e9-87f8-c70c5f855c87.png)

There will be one item in the JSON list for each host. 

The contents of these items are summarized in the SimGrid docs [here](http://simgrid.gforge.inria.fr/simgrid/3.20/doc/group__plugin__energy.html) (it's not too long).

Anytime a *pstate* is changed, we record the time and  new pstate, which then is added to *pstate_trace*. So this can be one graph. 

In WRENCH simulations, if a has recorded the total energy consumption of a host at any time, that gets added to *consumed_energy_trace*. So this could be another graph.
