### ISSUE TITLE
Obtaining Idle and total cores by methods getNumIdleCores() and getNumCores()  in the class ComputeService

### ISSUE THREAD

**Issue by GnimEd** [wrench-project/wrench#92]
For obtaining the total and idle number of cores, what is the interest of using `std::vector<unsigned long>` as return type, and why not `unsigned long` or `int` ?
We can use "**S4U_Simulation::getHostNumCores(host_name)**" (because the return type is an "unsigned int") to initialize the total number of core. This number (S4U_Simulation :: getHostNumCores (host_name)) can be incremented and decremented according to the number of tasks that run on the compute service in order to obtain in real time the number of idle cores on a compute service.

**Comment by rafaelfsilva** [comment]
@GnimEd,

I have implemented functions to simply provide the total number of cores and idle cores for a compute service (3bb1233):

``` 
unsigned long ComputeService::getTotalNumCores()
unsigned long ComputeService::getTotalNumIdleCores();
```

We still provide the functions returning the maps since a `wrench::ComputeService` may have several hosts and each host with multiple cores, so depending on the algorithm, it may be important to know the number of cores per host (similar for number of idle cores).

Thank you!
